### ISSUE TITLE
defining select with the formula interface

### ISSUE THREAD

**Issue by biometrician** [EdwinKipruto/mfp2#68]
I am currently updating the code from an old project where we used `mfp` and replacing `mfp` with `mfp2`. In the example below, `select` should not have the default value. Unfortunately, when I use the "old" notation, `select` is ignored. There is not even an error message that another value of `select` is used in the fit. 
I have seen that I have to change select in the formula for each fp variable. If only one value of `select` applies to all variables, I don't understand why I can't define it by specifying `select` only once.

Here is my sample code.

```{r data}
library(mfp2)
data("pima")
dat1 <- pima[,c(2:10)]
names(dat1) <- c("Pregnancies",  "Glucose" ,  "BloodPressure",  "SkinThickness",   "Insulin" ,  "BMI" , "DiabetesPedigreeFunction" ,"Age",       "Outcome")
fit_new <- mfp2(Outcome~ fp(Pregnancies, df=4) + fp(Glucose, df=4)+
                         fp(BloodPressure, df=4) + fp(SkinThickness, df=4)+
                         fp(Insulin, df=4) + fp(BMI, df=4)+ 
                         fp(DiabetesPedigreeFunction, df=4) + fp(Age, df=4),
                        family = "binomial", data=dat1, select= 0.01, verbose=FALSE)
```

Thanks, 
Daniela

**Comment by EdwinKipruto** [comment]
Once you use the df() function, its parameters, including select, will be
used, and other parameters will be ignored. To set select, df, or alpha
only once, do not use the df() function.

The example code should be:

fit_new <- mfp2(Outcome ~ Pregnancies + Glucose + BloodPressure +
SkinThickness + Insulin + BMI + DiabetesPedigreeFunction + Age,
                family = "binomial", data = dat1, select = 0.01, df = 4,
verbose = FALSE)

**Comment by biometrician** [comment]
Hi Edwin, 
Thanks a lot for the clarification.

Maybe a warning or a hint would be helpful if someone uses df() in mfp2. Users of the old mfp package are used to the “old spelling” and I can imagine that others will also have this problem.

Best,
Daniela

**Comment by EdwinKipruto** [comment]
Documented
